GET http://localhost:3000/movies
Content-Type: application/json

{}

###
GET http://localhost:3000/movies/4
Content-Type: application/json

{}

###
POST  http://localhost:3000/movies
Content-Type: application/json

{
    "title": "Movie",
    "actor": "Actor",
    "yearOfProd": 1990,
    "IMDBrank": "30",
    "about": "test about"
}

###
DELETE  http://localhost:3000/movies/11
Content-Type: application/json

{}